Import('env', 'arch', 'common', 'messaging', 'visionipc')

renv = env.Clone()

rayutil = env.Library("rayutil", ['raylib/util.cc'], LIBS='raylib')
linked_libs = [visionipc, messaging, 'raylib', rayutil, common]
renv['LIBPATH'] += [f'#third_party/raylib/{arch}/']

mac_frameworks = []
if arch == "Darwin":
  mac_frameworks += ['OpenCL', 'CoreVideo', 'Cocoa', 'GLUT', 'CoreFoundation', 'OpenGL', 'IOKit']
elif arch == 'larch64':
  linked_libs += ['OpenCL', 'GLESv2', 'GL', 'EGL', 'wayland-client', 'wayland-egl']
else:
  linked_libs += ['OpenCL', 'dl', 'pthread']

renv.Program("spinner", ["raylib/spinner.cc"], LIBS=linked_libs, FRAMEWORKS=mac_frameworks)
renv.Program("watch3", ["raylib/watch3.cc", "raylib/elements/cameraview.cc"], LIBS=linked_libs, FRAMEWORKS=mac_frameworks)
