Import('env', 'arch', 'common', 'messaging', 'visionipc', 'cereal')

base_libs = [common, messaging, cereal, visionipc, 'm', 'ssl', 'crypto', 'pthread']

base_frameworks = []
if arch == "Darwin":
  base_frameworks.append('OpenCL')
else:
  base_libs.append('OpenCL')

replay_lib_src = ["replay.cc", "consoleui.cc", "camera.cc", "filereader.cc", "logreader.cc", "framereader.cc",
                  "route.cc", "util.cc", "api.cc", "seg_mgr.cc", "timeline.cc"]
replay_lib = env.Library("qt_replay", replay_lib_src, LIBS=base_libs, FRAMEWORKS=base_frameworks)
Export('replay_lib')
replay_libs = [replay_lib, 'avutil', 'avcodec', 'avformat', 'bz2', 'zstd', 'curl', 'yuv', 'ncurses'] + base_libs
env.Program("replay", ["main.cc"], LIBS=replay_libs, FRAMEWORKS=base_frameworks)

if GetOption('extras'):
  env.Program('tests/test_replay', ['tests/test_replay.cc'], LIBS=[replay_libs, base_libs])
