Import('env', 'arch', 'SHARED', 'common')
if SHARED:
  fxn = env.SharedLibrary
else:
  fxn = env.Library

hardware_libs = []
if arch == "aarch64":
   hardware_libs = ['eon/hardware.cc']
elif arch == "larch64":
  hardware_libs = ['tici/hardware.cc']
else:
  hardware_libs = ['pc/hardware.cc']
  pass

_hardware = fxn('hardware', hardware_libs)
Export('_hardware')
